language: ruby
rvm:
  - "1.9.3-p551"
  - "2.0.0-p598"
  - "2.1.6"
  - "2.2.2"
install: bundle install --binstubs
env: TRAVIS_BUILD=true
matrix:
  allow_failures:
    - rvm: "1.9.3-p551"
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/60e610197dad8edc59f9
    on_success: always
    on_failure: always
    on_start: false
